apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiveapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receiveapi
  template:
    metadata:
      labels:
        app: receiveapi
    spec:
      containers:
      - name: receiveapi
        image: receiveapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: receiveapi-service
spec:
  selector:
    app: receiveapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
